
# Here is a dictonary contai "Questions", "Option" & "Solution"
Quiz_game = {
    1: {
        "question": "What is the name of main character in 'Naruto'?",
        "options": {
            "a": "Sasuke Uchiha",
            "b": "Sakura Haruno",
            "c": "Naruto Uzumaki",
            "d": "Kakashi Hatake"
        },
    },
}


print(f"1. {Quiz_game[1]["question"]}")
print(f"1. {Quiz_game[1]["options"]["a"]}\n,{Quiz_game[1]["options"]["b"]}\n,{Quiz_game[1]["options"]["c"]},{Quiz_game[1]["options"]["d"]}")
